# Generated by Django 5.1.4 on 2025-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
